---

- hosts: localhost
  become: true
  tasks:

  - name: DNF Update
    dnf:
      name: "*"
      state: latest

  - name: Install Gnome and Applications
    dnf:
      state: latest
      name:
        - gnome-shell
        - gnome-terminal
        - gnome-tweaks
        - gnome-software
        - gnome-system-monitor
        - gnome-disk-utility
        - nautilus
        - gvfs-smb
        - gvfs-nfs
        - nfs-utils
        - plymouth
        - plymouth-system-theme
        - plymouth-theme-spinfinity
        - flatpak
        - git
        - rsync
        - borgbackup
        - openssh

  - name: Add the flathub flatpak repository
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install Flatpaks
    community.general.flatpak:
      name:
        - org.mozilla.firefox
        - com.google.Chrome
        - com.spotify.Client
        - org.gnome.World.PikaBackup
        - com.bitwarden.desktop
        - com.visualstudio.code
        - com.mojang.Minecraft
        - org.libreoffice.LibreOffice
        - com.mattjakeman.ExtensionManager

  - name: Remove OpenSSH server
    ansible.builtin.systemd_service:
      name: openssh-server
      state: absent
      
  - name: Disable default
    ansible.builtin.systemd_service:
      name: default.target
      enabled: false

  - name: Enable desktop
    ansible.builtin.systemd_service:
      name: graphical.target
      enabled: true
