version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:5.0.13
    volumes:
      - mongodb:/data/db
    networks:
      - graylog

  opensearch:
    container_name: opensearch
    restart: always
    image: opensearchproject/opensearch:2.4.0
    volumes:
      - os_data:/usr/share/opensearch/data
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - graylog

  graylog:
    container_name: graylog
    restart: always
    image: graylog/graylog:5.1.2
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PW_SECRET}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PW}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/config/node-id
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    links:
      - mongodb:mongo
      - opensearch
    depends_on:
      mongodb:
        condition: "service_started"   
      opensearch:
        condition: "service_started"
    ports:
      - 9000:9000	# Graylog port
      - 514:1514	# Syslog TCP
      - 514:1514/udp    # Syslog UDP
      - 2055:2055/udp	# Netfloww UDP
    networks:
      - graylog
 
volumes:
  graylog_data:
    driver: local
  mongodb:
    driver: local
  os_data:
    driver: local

networks:
  graylog:

