version: "3"

services:
  nginx:
    container_name: nginx_reverse
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./reverse.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx

networks:
  nginx:
