- name: Install Gnome Desktop
  hosts: localhost
  become: true
  tasks:
    - name: System Update 
      community.general.pacman:
         update_cache: true
         upgrade: true

    - name: Plasma Desktop
      community.general.pacman:
        name:
          - plasma-desktop
          - xorg-server
          - xorg-xwayland
          - sddm
          - sddm-kcm
          - avahi
          - plasma-wayland-protocols
          - firewalld
          - plasma-firewall
          - plasma-nm
          - kde-gtk-config
          - konsole
          - dolphin
          - plasma-systemmonitor
          - discover
          - networkmanager
          - acpi
          - acpid
          - cups
          - cups-browsed
          - nfs-utils
          - xdg-user-dirs
          - xdg-desktop-portal
          - plymouth
          - packagekit
          - packagekit-qt5
          - packagekit-qt6
          - fwupd
          - reflector
          - git
          - rsync
          - borg
          - flatpak
        state: present

    - name: Add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpaks
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - com.google.Chrome
          - com.spotify.Client
          - org.gnome.World.PikaBackup
          - org.gnome.gedit
          - com.bitwarden.desktop
          - com.visualstudio.code
          - com.mojang.Minecraft
          - org.libreoffice.LibreOffice

    - name: Start Cups
      ansible.builtin.systemd_service:
        enabled: true
        name: cups

    - name: Start Acpid    
      ansible.builtin.systemd_service:
        enabled: true
        name: acpid

    - name: Start Avahi-Daemon    
      ansible.builtin.systemd_service:
        enabled: true
        name: avahi-daemon

    - name: Start SDDM    
      ansible.builtin.systemd_service:
        enabled: true
        name: sddm
